"use strict";

// The producer name is a logical contract; render-model validation uses the
// generic runtime identity until that runtime intentionally grows aliases.
export const LOGICAL_PROFILE = "csm-review-human/1";
export const RUNTIME_PROFILE = { id: "csm-render-profile/1", revision: 1 };
export const SOURCE_REF = { id: "csm-review-findings/1", revision: 1 };

// This is the normalized source view consumed by the generic model builder,
// not the findings JSON Schema. Repeated finding details live in table rows.
export const HUMAN_SOURCE_SCHEMA = {
  $id: "csm-review-findings/1",
  revision: 1,
  artifact: {
    artifactId: {},
    owner: {},
    runId: {},
    digest: {},
    createdAt: {},
  },
  source: { commitSha: {}, repository: {} },
  schema: {},
  schemaRevision: {},
  findings: {},
  verificationStatus: { status: {}, unresolved: {} },
  redaction: { status: {}, rules: {}, redactedFields: {} },
  sortOrder: { algorithm: {}, stable: {} },
  ownership: { collisionPolicy: {}, terminalPolicy: {} },
  projection: { authority: {}, formats: {} },
};

export const HUMAN_PROFILE = {
  schema: "csm-render-profile/1",
  profile: RUNTIME_PROFILE,
  sourceSchema: SOURCE_REF,
  sections: [
    { id: "summary", label: "Summary", order: 0 },
    { id: "findings", label: "Findings", order: 1 },
    { id: "detail", label: "Detail", order: 2 },
    { id: "review-evidence", label: "Review Evidence", order: 3 },
    { id: "provenance", label: "Provenance", order: 4 },
  ],
  fields: [
    {
      path: "/artifact/artifactId",
      kind: "text",
      label: "Review artifact",
      accessibleLabel: "Review artifact identifier",
      visibility: "always",
      order: 0,
      section: "summary",
    },
    {
      path: "/verificationStatus/status",
      kind: "text",
      label: "Verification status",
      accessibleLabel: "Overall verification status",
      visibility: "always",
      order: 1,
      section: "summary",
    },
    {
      path: "/source/commitSha",
      kind: "text",
      label: "Source commit",
      accessibleLabel: "Repository source commit",
      visibility: "always",
      order: 2,
      section: "summary",
    },
    {
      path: "/findings",
      kind: "table",
      label: "Finding records",
      accessibleLabel: "Findings ordered by severity, confidence, evidence class, and identifier",
      visibility: "always",
      order: 0,
      section: "findings",
    },
    {
      path: "/source/repository",
      kind: "text",
      label: "Repository",
      accessibleLabel: "Reviewed repository",
      visibility: "if-present",
      order: 0,
      section: "detail",
    },
    {
      path: "/artifact/createdAt",
      kind: "date",
      label: "Review created",
      accessibleLabel: "Review creation time",
      visibility: "always",
      order: 1,
      section: "detail",
    },
    {
      path: "/sortOrder/algorithm",
      kind: "text",
      label: "Finding order",
      accessibleLabel: "Authoritative finding ordering algorithm",
      visibility: "always",
      order: 2,
      section: "detail",
    },
    {
      path: "/sortOrder/stable",
      kind: "boolean",
      label: "Stable ordering",
      accessibleLabel: "Whether finding ordering is stable",
      visibility: "always",
      order: 3,
      section: "detail",
    },
    {
      path: "/schema",
      kind: "text",
      label: "Findings schema",
      accessibleLabel: "Findings schema identity",
      visibility: "always",
      order: 4,
      section: "detail",
    },
    {
      path: "/schemaRevision",
      kind: "number",
      label: "Schema revision",
      accessibleLabel: "Findings schema revision",
      visibility: "always",
      order: 5,
      section: "detail",
    },
    {
      path: "/verificationStatus/unresolved",
      kind: "list",
      label: "Unresolved verification items",
      accessibleLabel: "Unresolved verification items",
      visibility: "always",
      order: 0,
      section: "review-evidence",
    },
    {
      path: "/redaction/redactedFields",
      kind: "number",
      label: "Redacted fields",
      accessibleLabel: "Number of redacted fields",
      visibility: "always",
      order: 1,
      section: "review-evidence",
    },
    {
      path: "/redaction/rules",
      kind: "list",
      label: "Redaction rules",
      accessibleLabel: "Rules applied during review redaction",
      visibility: "always",
      order: 3,
      section: "review-evidence",
    },
    {
      path: "/redaction/status",
      kind: "text",
      label: "Redaction status",
      accessibleLabel: "Review redaction status",
      visibility: "always",
      order: 2,
      section: "review-evidence",
    },
    {
      path: "/artifact/runId",
      kind: "text",
      label: "Review run",
      accessibleLabel: "Review run identifier",
      visibility: "always",
      order: 0,
      section: "provenance",
    },
    {
      path: "/artifact/owner",
      kind: "text",
      label: "Review owner",
      accessibleLabel: "Review producer owner",
      visibility: "always",
      order: 1,
      section: "provenance",
    },
    {
      path: "/artifact/digest",
      kind: "text",
      label: "Review digest",
      accessibleLabel: "Canonical review artifact digest",
      visibility: "always",
      order: 2,
      section: "provenance",
    },
    {
      path: "/ownership/collisionPolicy",
      kind: "text",
      label: "Collision policy",
      accessibleLabel: "Artifact collision policy",
      visibility: "always",
      order: 3,
      section: "provenance",
    },
    {
      path: "/ownership/terminalPolicy",
      kind: "text",
      label: "Terminal policy",
      accessibleLabel: "Artifact terminal policy",
      visibility: "always",
      order: 4,
      section: "provenance",
    },
    {
      path: "/projection/authority",
      kind: "text",
      label: "Projection authority",
      accessibleLabel: "Projection authority status",
      visibility: "always",
      order: 5,
      section: "provenance",
    },
    {
      path: "/projection/formats",
      kind: "list",
      label: "Projection formats",
      accessibleLabel: "Available human projection formats",
      visibility: "always",
      order: 6,
      section: "provenance",
    },
  ],
  urlPolicy: { mode: "deny", schemes: [] },
  unsupported: [
    "raw challenge, dissent, and verification rationale/command/result values",
    "raw finding object paths and dynamic /findings/N paths",
    "raw JSON Schema documents and arbitrary Markdown or HTML",
  ],
};

export const REDACTION_POLICY = {
  nested: {
    challengeRationale: "marker",
    dissentRationale: "marker",
    verificationCommand: "marker",
    verificationResult: "marker",
  },
  marker: "[REDACTED]",
  rule: "Never emit nested redacted values as ordinary text; preserve only their marker.",
};

export const FINDINGS_FIELD_MAPPING = [
  ["id", "Finding ID", "table"],
  ["title", "Title", "table"],
  ["dimension", "Dimension", "table"],
  ["category", "Category", "table"],
  ["anchorRef", "Anchor", "table"],
  ["severity", "Severity", "table"],
  ["confidence", "Confidence", "table"],
  ["evidenceClass", "Evidence class", "table"],
  ["locations", "Locations", "table"],
  ["quotedSnippets", "Quoted snippets", "table"],
  ["commitSha", "Finding commit", "table"],
  ["explanation", "Explanation", "table"],
  ["impact", "Impact", "table"],
  ["remediationSketch", "Remediation", "table"],
  ["fixActions", "Fix actions", "table"],
  ["verification.method", "Verification method", "table"],
  ["challenges.verdict", "Challenge verdict", "table"],
  ["dissents", "Dissent presence", "table"],
  ["status", "Status", "table"],
  ["statusNote", "Status note", "table"],
  ["corroborators", "Corroborators", "table"],
  ["sortKey", "Sort key", "table"],
  ["cvss", "CVSS metadata", "table"],
  ["schema", "Findings schema", "detail"],
  ["schemaRevision", "Schema revision", "detail"],
  ["verificationStatus", "Verification status", "summary"],
  ["redaction.rules", "Redaction rules", "review-evidence"],
  ["sortOrder.stable", "Stable ordering", "detail"],
  ["ownership.collisionPolicy", "Collision policy", "provenance"],
  ["ownership.terminalPolicy", "Terminal policy", "provenance"],
  ["projection.authority", "Projection authority", "provenance"],
  ["projection.formats", "Projection formats", "provenance"],
  ["verification.command", "Omitted: redacted verification command", "marker-only"],
  ["verification.result", "Omitted: redacted verification result", "marker-only"],
  ["fixActions.verification", "Omitted: potentially sensitive fix verification", "marker-only"],
  ["challenges.rationale", "Omitted: redacted challenge rationale", "marker-only"],
  ["dissents.rationale", "Omitted: redacted dissent rationale", "marker-only"],
];
