"use strict";
// T008/P6: the csm-orchestrate node/run evaluator + bounded remainder +
// typed resumable supersession. Proves that a hard node failure stops the run
// closed while recording the abandoned work as a typed, resumable supersession
// (with the pending nodes/phases), and that at most one bounded remainder phase
// can ever be directed by the evaluator.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { orchestrate } from "../csm-orchestrate/lib/index.mjs";
import { validateCapabilities } from "../csm-orchestrate/lib/capabilities.mjs";
import { RUN_EVALUATOR_CONTRACT, evaluateRunRemainder } from "../csm-orchestrate/lib/recovery.mjs";
import { createArtifactResolver } from "../lib/artifact-resolver/index.mjs";
import { digest, loadSchemaRegistry } from "../lib/schema-runtime/index.mjs";

const ROOT = new URL("../", import.meta.url);
const SHA_A = "sha256:" + "a".repeat(64);
const SHA_B = "sha256:" + "b".repeat(64);
const NOW = () => new Date("2026-09-19T12:00:00Z");
const sha256 = (bytes) => "sha256:" + createHash("sha256").update(bytes).digest("hex");

// The branch's capabilities.json is regenerated by the serialized T011/T012
// steps, so its recorded source digests can lag the working tree. Recompute the
// manifest digests from the actual sources to exercise the run loop without
// weakening the production digest checks (validateCapabilities still runs).
async function trustedCapabilities() {
  const manifest = JSON.parse(
    await readFile(new URL("csm-orchestrate/capabilities.json", ROOT), "utf8"),
  );
  for (const capability of manifest.skills) {
    capability.digest = sha256(await readFile(new URL(capability.source.skillPath, ROOT)));
    if (capability.source.entrypoint && capability.source.libraryDigest)
      capability.source.libraryDigest = sha256(
        await readFile(new URL(capability.source.entrypoint, ROOT)),
      );
  }
  manifest.contentDigest = digest(manifest.skills);
  return validateCapabilities(manifest);
}

// csm-ddd is dependency-free read-only; csm-grill is serial and depends on the
// preceding node, so when csm-ddd fails csm-grill is left genuinely pending.
const SIGNALS = { capabilities: ["csm-ddd", "csm-grill"] };

const approachFor = (runId) => ({
  schema: "csm-approach/1",
  schemaRevision: 1,
  status: "agreed",
  runId,
  ideaSlug: "remainder",
  signals: SIGNALS,
  phases: [
    {
      phaseId: "P1",
      title: "Deliver",
      goal: "produce the deliverable",
      deliverables: ["typed result"],
      scope: ["repository"],
      outOfScope: ["production"],
      constraints: [],
      acceptanceHints: ["technical pass", "functional pass"],
      context: [],
      dependencies: [],
    },
  ],
});

function failingHost({ failSkills = ["csm-ddd"] } = {}) {
  const failing = new Set(failSkills);
  const callsBySkill = new Map();
  let calls = 0;
  const artifacts = new Map();
  return {
    get calls() {
      return calls;
    },
    get callsBySkill() {
      return new Map(callsBySkill);
    },
    async invokeSiblingSkill(request) {
      calls += 1;
      callsBySkill.set(request.skill, (callsBySkill.get(request.skill) ?? 0) + 1);
      if (failing.has(request.skill))
        return {
          status: "failed",
          failure: {
            class: "policy",
            code: "node-hard-failure",
            message: `planned hard failure for ${request.skill}`,
          },
        };
      const descriptorBody = {
        schema: "csm-orchestrate-evidence/2",
        evidenceId: `ev-remainder-${calls}`,
        kind: "technical",
        status: "current",
        owner: request.skill,
        runId: request.childRunId,
        requirementIds: [request.phaseId.replace(/^phase-/, "req-")],
        acceptanceSignalId: request.acceptanceSignalIds?.[0],
        source: {
          path: `fixture-${request.childRunId}.json`,
          artifactId: `art-${request.childRunId}`,
          digest: SHA_A,
          schema: "csm-orchestrate-evidence/2",
          sourceRunId: request.childRunId,
        },
      };
      const descriptor = { ...descriptorBody, digest: SHA_B };
      artifacts.set(descriptorBody.source.path, descriptor);
      return {
        status: "completed",
        technical: [{ id: "technical", status: "pass", evidenceRefs: [descriptor.evidenceId] }],
        functional: [{ id: "functional", status: "pass", evidenceRefs: [descriptor.evidenceId] }],
        evidence: [descriptor],
        childReceipt: {
          receiptId: `receipt-remainder-${calls}`,
          schema: "csm-orchestrate-child-receipt/1",
          runId: request.childRunId,
          digest: SHA_B,
          owner: request.skill,
          status: "completed",
        },
      };
    },
    artifactResolver: {
      async resolve(refPath) {
        const value = artifacts.get(refPath);
        if (!value) return { status: "missing", code: "missing", message: `missing ${refPath}` };
        return { status: "resolved", path: refPath, value };
      },
    },
  };
}

const buildApproval = async ({ phase, node, childRunId }) => {
  if (!phase || !node || !childRunId) return undefined;
  const approvedAt = new Date(NOW());
  return {
    schema: "csm-orchestrate-approval/2",
    approvalId: `approval-${childRunId}`,
    binding: {
      parentRunId: phase.runId,
      childRunId,
      phaseId: phase.phaseId,
      edgeId: `edge-${node.nodeId}`,
    },
    scope: [...node.approvalScope],
    approvedDigest: node.capabilityDigest,
    approvedAt: approvedAt.toISOString(),
    expiresAt: new Date(approvedAt.getTime() + 3_600_000).toISOString(),
    status: "approved",
  };
};

const memoryCursorStore = () => ({
  cursors: new Map(),
  async saveCursor(cursor) {
    this.cursors.set(cursor.cursorId, cursor);
  },
  async loadCursor(cursorId) {
    return this.cursors.get(cursorId) ?? null;
  },
});

async function orchestrateOptions(runId, host, extra = {}) {
  const reviewArtifactRoot = await mkdtemp(join(tmpdir(), "remainder-review-"));
  const schemaRegistry = await loadSchemaRegistry();
  return {
    approach: approachFor(runId),
    runId,
    host,
    capabilities: await trustedCapabilities(),
    signals: SIGNALS,
    approvals: buildApproval,
    now: NOW,
    cursorStore: memoryCursorStore(),
    schemaRegistry,
    artifactResolver: createArtifactResolver({ root: reviewArtifactRoot, schemaRegistry }),
    childArtifactResolver: host.artifactResolver,
    retryBackoffMs: 0,
    ...extra,
  };
}

test("evaluator contract is typed, binding, and fail-closed", () => {
  assert.equal(RUN_EVALUATOR_CONTRACT.format, "csm-evaluator-contract/1");
  assert.ok(RUN_EVALUATOR_CONTRACT.outputs.includes("remainder"));
  assert.match(RUN_EVALUATOR_CONTRACT.binding, /bounded to one phase/);
  assert.equal(RUN_EVALUATOR_CONTRACT.receipt, "journaled");
});

test("evaluator records a typed resumable supersession and bounds remainders to one", () => {
  const failure = {
    status: "failed",
    failure: { class: "policy", code: "node-hard-failure" },
  };
  const first = evaluateRunRemainder({
    runId: "run-remainder-eval",
    phaseId: "phase-remainder-eval",
    failedNodeId: "node-a",
    failure,
    pendingNodes: ["node-b"],
    pendingPhases: ["phase-later"],
    remaindersUsed: 0,
    remainderPolicy: { maxRemainders: 1 },
  });
  assert.equal(first.verdict, "remainder");
  assert.equal(first.failClosed, true);
  assert.equal(first.remainder.bounded, true);
  assert.equal(first.remainder.budget, 1);
  assert.equal(first.supersession.schema, "csm-orchestrate-supersession/1");
  assert.equal(first.supersession.resumable, true);
  assert.equal(first.supersession.failClosed, true);
  assert.deepEqual([...first.supersession.pendingNodes], ["node-b"]);
  assert.deepEqual([...first.supersession.pendingPhases], ["phase-later"]);

  const second = evaluateRunRemainder({
    runId: "run-remainder-eval",
    phaseId: "phase-remainder-eval",
    failedNodeId: "node-b",
    failure,
    pendingNodes: ["node-c"],
    remaindersUsed: 1,
    remainderPolicy: { maxRemainders: 1 },
  });
  assert.equal(second.verdict, "blocked");
  assert.equal(second.remainder, null);
  assert.equal(second.supersession.remainderSpent, true);

  const denied = evaluateRunRemainder({
    runId: "run-remainder-eval",
    phaseId: "phase-remainder-eval",
    failure,
    pendingNodes: ["node-b"],
    remainderPolicy: { maxRemainders: 0 },
  });
  assert.equal(denied.verdict, "blocked");
});

test("a hard node failure stops the run closed and records a resumable supersession", async () => {
  const runId = "run-remainder-failclosed";
  const host = failingHost();
  const result = await orchestrate(await orchestrateOptions(runId, host));

  assert.equal(result.receipt.outcome.status, "FAILED");
  assert.equal(result.receipt.outcome.accepted, false);
  assert.equal(host.calls, 1, "the default policy directs no remainder");

  const supersession = result.supersession;
  assert.ok(supersession, "the run must emit a typed resumable supersession");
  assert.equal(supersession.schema, "csm-orchestrate-supersession/1");
  assert.equal(supersession.resumable, true);
  assert.equal(supersession.failClosed, true);
  assert.equal(supersession.failedNodeId, "node-p1-csm-ddd");
  assert.deepEqual([...supersession.pendingNodes], ["node-p1-csm-grill"]);

  const remainderPhases = result.receipt.extensions.phaseSummaries.filter(
    (item) => item.parentPhaseId,
  );
  assert.equal(remainderPhases.length, 0, "the default policy runs no remainder");
});

test("the durable cursor records the resumable supersession pointer", async () => {
  const runId = "run-remainder-durable";
  const host = failingHost();
  const options = await orchestrateOptions(runId, host);
  const result = await orchestrate(options);
  const stored = [...options.cursorStore.cursors.values()].find(
    (cursor) => cursor.terminalIntent?.resumableSupersession,
  );
  assert.ok(stored, "the supersession pointer must be persisted durably");
  assert.equal(
    stored.terminalIntent.resumableSupersession.schema,
    "csm-orchestrate-supersession/1",
  );
  assert.deepEqual(
    [...stored.terminalIntent.resumableSupersession.pendingNodes],
    ["node-p1-csm-grill"],
  );
  assert.equal(result.receipt.outcome.status, "FAILED");
});

test("at most one bounded remainder phase runs, then the run stops closed", async () => {
  const runId = "run-remainder-bounded";
  const host = failingHost({ failSkills: ["csm-ddd", "csm-grill"] });
  const options = await orchestrateOptions(runId, host, {
    remainderPolicy: { maxRemainders: 1 },
  });
  const result = await orchestrate(options);

  assert.equal(result.receipt.outcome.status, "FAILED");
  assert.equal(result.receipt.outcome.accepted, false);
  assert.equal(host.calls, 2, "one original attempt plus exactly one remainder");
  assert.equal(host.callsBySkill.get("csm-ddd"), 1);
  assert.equal(host.callsBySkill.get("csm-grill"), 1);
  const remainders = result.receipt.extensions.phaseSummaries.filter((item) => item.parentPhaseId);
  assert.equal(remainders.length, 1, "exactly one bounded remainder phase ran");
  const remainderContract = result.receipt.extensions.phaseContracts.find(
    (item) => item.parentPhaseId,
  );
  assert.ok(remainderContract, "the remainder phase contract is recorded");
  assert.equal(
    options.schemaRegistry.validate("csm-orchestrate-phase/2", remainderContract).valid,
    true,
  );
  assert.equal(result.supersession.schema, "csm-orchestrate-supersession/1");
  assert.equal(result.supersession.resumable, true);
});
