import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readdir, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';

import { enrich } from '../lib/scan/enrich.mjs';
import { validate } from '../lib/scan/validate.mjs';
import { writeNORMS } from '../lib/scan/write.mjs';
import { fixedInput, semanticProjection } from './helpers/expansion-shared.mjs';
import { collectTestNames } from './helpers/collect-test-names.mjs';

const TEST_ROOT = dirname(fileURLToPath(import.meta.url));
const BASELINE_ROOT = join(TEST_ROOT, 'baselines', 'expansion');

async function readJson(name) {
  return JSON.parse(await readFile(join(BASELINE_ROOT, name), 'utf8'));
}

function digest(source) {
  return createHash('sha256').update(source).digest('hex');
}

async function lockApplies(lock) {
  try {
    return digest(await readFile(join(TEST_ROOT, '..', lock.path))) === lock.sha256;
  } catch (error) {
    if (error.code === 'ENOENT') return false;
    throw error;
  }
}

async function currentResult() {
  const { overview, deep } = fixedInput();
  const enriched = await enrich(deep, overview);
  return { overview, enriched, validated: await validate(enriched) };
}

test('T201 semantic baseline preserves the existing ten dimensions and result keys', async () => {
  const expected = await readJson('semantic.json');
  const { enriched, validated } = await currentResult();
  assert.deepEqual(semanticProjection(enriched, validated), expected);
  assert.equal(validated.findings.length, 10);
  assert.equal(validated.needsRetry.length, 0);
});

test('T201 fixed-input renderer output matches the deterministic Markdown baseline', async () => {
  const expected = await readFile(join(BASELINE_ROOT, 'renderer.md'), 'utf8');
  const { overview, validated } = await currentResult();
  const root = await mkdtemp(join(tmpdir(), 'csm-scan-expansion-render-'));
  try {
    const content = await writeNORMS({ generated: '2026-01-15', repos: [{ overview, deep: validated.findings }] }, join(root, 'NORMS.md'));
    assert.equal(content, expected);
    assert.equal(content.includes(root), false);
    assert.match(content, /> Generated by csm-scan on 2026-01-15/);
    assert.match(content, /- \*\*Path\*\*: `\.`/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('T201 inventory binds the acceptance command to five fixture pipelines and all 21 P0 tests', async () => {
  const expected = await readJson('inventory.json');
  assert.deepEqual(expected.acceptanceTestFiles, [
    'test/expansion-baseline.test.mjs',
    'test/expansion-constraints.test.mjs',
    'test/fixtures-pipeline.test.mjs',
    'test/regression-parity.test.mjs',
    'test/expansion-command-core.test.mjs',
    'test/expansion-command-deep.test.mjs',
    'test/expansion-privacy-write.test.mjs',
  ]);
  assert.deepEqual(expected.recurringAcceptanceTestFiles, expected.acceptanceTestFiles);
  const fixtureUrl = new URL('./fixtures/', import.meta.url);
  const fixtureModules = (await readdir(join(TEST_ROOT, 'fixtures')))
    .filter((name) => name.endsWith('.mjs'))
    .toSorted();
  for (const moduleName of fixtureModules) {
    const module = await import(new URL(moduleName, fixtureUrl));
    assert.equal(typeof module.files, 'object', `${moduleName} must export files`);
  }
  assert.deepEqual([...fixtureModules].toSorted(), expected.fixtureModules);

  // T010 (F-038): registered test names are collected through the real runner,
  // never by regexing the test files' source text.
  const collected = await collectTestNames([
    join(TEST_ROOT, 'fixtures-pipeline.test.mjs'),
    join(TEST_ROOT, 'regression-parity.test.mjs'),
  ]);
  assert.equal(collected.code, 0, `runner exited ${collected.code}\n${collected.stderr}`);
  assert.deepEqual(collected.failures, [], `registered gate tests failed: ${collected.failures.join(', ')}`);
  assert.deepEqual(collected.skips, [], `registered gate tests skipped: ${collected.skips.join(', ')}`);
  const fixtureCases = collected.names
    .filter((name) => /^T020 \w+ fixture:/.test(name))
    .map((name) => name.match(/^T020 (\w+) fixture:/)[1]);
  assert.deepEqual(fixtureCases, expected.fixtureCases);
  assert.deepEqual(
    collected.names.filter((name) => name.startsWith('P0-')),
    expected.p0TestNames,
    'every P0 parity case must be registered by name',
  );
});

test('T201 reviewed test and fixture inputs stay registered and non-skipped', async () => {
  // T010 (F-034): the byte-hash lock (test-integrity.json) was replaced with
  // behavioral constraints — the reviewed fixture modules must still export
  // non-empty file sets, and the reviewed test inputs must still register
  // executable tests with zero failures and zero skips.
  const fixtureUrl = new URL('./fixtures/', import.meta.url);
  for (const moduleName of [
    'javascript.mjs', 'python.mjs', 'rust.mjs', 'shell.mjs', 'typescript.mjs',
  ]) {
    const module = await import(new URL(moduleName, fixtureUrl));
    assert.ok(module.files && Object.keys(module.files).length > 0,
      `${moduleName} must export non-empty files`);
  }
  const collected = await collectTestNames([
    join(TEST_ROOT, 'expansion-command-deep.test.mjs'),
    join(TEST_ROOT, 'fixtures-pipeline.test.mjs'),
    join(TEST_ROOT, 'regression-parity.test.mjs'),
  ]);
  assert.equal(collected.code, 0, `runner exited ${collected.code}\n${collected.stderr}`);
  assert.deepEqual(collected.failures, [], `reviewed tests failed: ${collected.failures.join(', ')}`);
  assert.deepEqual(collected.skips, [], `reviewed tests skipped: ${collected.skips.join(', ')}`);
  assert.ok(collected.names.length > 0, 'reviewed test inputs must register executable tests');
});

test('T201 supersession records are legacy locks or live recurring replacements', async () => {
  const baseline = await readJson('supersession.json');
  const inventory = await readJson('inventory.json');
  const expectedIds = [
    'host-runtime-probes',
    'personal-identity-output',
    'free-form-na',
    'coverage-status-representation',
    'deterministic-ordering-paths',
  ];
  assert.equal(baseline.version, 1);
  assert.deepEqual(baseline.entries.map(({ id }) => id), expectedIds);
  assert.match(baseline.policy, /legacy_locked/);
  assert.match(baseline.policy, /recurring acceptance inventory/);
  for (const entry of baseline.entries) {
    assert.ok(['legacy_locked', 'superseded'].includes(entry.state), `${entry.id} has an invalid state`);
    assert.match(entry.replacementTask, /^T\d+$/);
    assert.ok(entry.legacyLocks.length > 0, `${entry.id} must retain legacy evidence`);
    assert.ok(entry.legacyLocks.some(({ role }) => role === 'production'));
    assert.ok(entry.legacyLocks.some(({ role }) => role === 'test'));
    const lockResults = await Promise.all(entry.legacyLocks.map(lockApplies));
    if (entry.state === 'legacy_locked') {
      assert.equal(entry.replacement, null);
      assert.ok(lockResults.every(Boolean), `${entry.id} legacy locks changed before ${entry.replacementTask}`);
      continue;
    }
    assert.ok(lockResults.some((applies) => !applies), `${entry.id} cannot be superseded while every legacy lock applies`);
    assert.ok(inventory.recurringAcceptanceTestFiles.includes(entry.replacement.testFile));
    // T010 (F-034): the replacement-test byte-hash lock was replaced with a
    // behavioral constraint — the exact replacement test name must be
    // REGISTERED by the real runner (and pass), never merely present in source.
    const collected = await collectTestNames([
      join(TEST_ROOT, '..', entry.replacement.testFile),
    ]);
    assert.equal(collected.code, 0,
      `${entry.id}: replacement test file exited ${collected.code}\n${collected.stderr}`);
    assert.ok(collected.names.includes(entry.replacement.testName),
      `${entry.id} replacement test is not registered under its exact name`);
    assert.ok(!collected.failures.includes(entry.replacement.testName),
      `${entry.id} replacement test failed to pass`);
    assert.ok(!collected.skips.includes(entry.replacement.testName),
      `${entry.id} replacement test must not be skipped`);
  }
});
