import { writeFile } from 'node:fs/promises';

import { DEFAULT_RENDER_CONTEXT, finalizeMarkdown } from './render/base.mjs';
import { DEFAULT_EXISTING_TEN_RENDERER } from './render/existing-ten.mjs';

const { escapeField } = DEFAULT_RENDER_CONTEXT;

function overviewSection(overview) {
  if (!overview) return '';
  const lines = [];
  lines.push('## Repository Overview');
  lines.push('');
  lines.push(`- **Name**: ${escapeField(overview.name || 'unknown')}`);
  lines.push(`- **Path**: \`${escapeField(overview.path || '')}\``);
  lines.push(`- **Languages**: ${escapeField((overview.languages || []).join(', ') || 'none detected')}`);
  lines.push(`- **Package Manager**: ${escapeField(overview.packageManager || 'unknown')}`);
  lines.push(`- **Total Files**: ${overview.totalFiles || 0}`);
  if (overview.isGit) lines.push(`- **Git**: yes (${escapeField(overview.gitRoot || '')})`);
  if (overview.description) lines.push(`- **Description**: ${escapeField(overview.description)}`);
  lines.push('');
  return lines.join('\n');
}

function crossObservationsSection(contradictions) {
  if (!Array.isArray(contradictions) || contradictions.length === 0) return '';
  const lines = [];
  lines.push('## Cross-observations');
  lines.push('');
  for (const c of contradictions) {
    lines.push(`- ${escapeField(c.description || '')}`);
  }
  lines.push('');
  return lines.join('\n');
}

export async function writeNORMS(findings, outPath, renderer = DEFAULT_EXISTING_TEN_RENDERER) {
  if (renderer === null || renderer === undefined || typeof renderer.render !== 'function') {
    throw new TypeError('writeNORMS requires a renderer with a render(deep) method');
  }
  const lines = [];
  const firstRepo = findings.repos[0];
  const firstOverview = firstRepo?.overview;
  const titleRepo = firstOverview?.name || firstRepo?.overview?.name || 'unknown';

  lines.push(`# NORMS — ${escapeField(titleRepo)}`);
  lines.push('');
  lines.push(`> Generated by csm-scan on ${findings.generated}`);
  if (findings.repos.length > 1) {
    const names = findings.repos.map((r) => r.overview?.name || 'unknown').join(', ');
    lines.push(`> Scanned repos: ${escapeField(names)}`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('### Coverage Basis');
  lines.push('');
  lines.push('| Basis | Meaning |');
  lines.push('|-------|---------|');
  lines.push('| `observed` | Scanner fields reported directly from repository artifacts |');
  lines.push('| `inferred` | Scanner fields reported with one or more derived repository patterns |');
  lines.push('| `unverified` | No top-level scanner fields reported |');
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const repo of findings.repos) {
    lines.push(overviewSection(repo.overview));
    lines.push(...renderer.render(repo.deep));

    if (Array.isArray(repo.crossObservations)) {
      const section = crossObservationsSection(repo.crossObservations);
      if (section) lines.push(section);
    } else if (findings.repos.length === 1 && findings.contradictions) {
      const section = crossObservationsSection(findings.contradictions);
      if (section) lines.push(section);
    }
  }

  if (findings.global !== undefined && findings.global !== null
      && typeof renderer.renderGlobal === 'function') {
    const globalSection = renderer.renderGlobal(findings.global);
    if (globalSection) lines.push(globalSection);
  }

  const content = finalizeMarkdown(lines);
  await writeFile(outPath, content, 'utf-8');
  return content;
}
