const MANIFEST = {
  "csm-grill": {
    sections: [
      "Interface",
      "Activation Boundary",
      "Core Rules",
      "Grilling State Machine",
      "Anti-Patterns",
      "Done Criteria",
    ],
    tmux: false,
    norms: false,
    machine: { section: "Grilling State Machine", entryExit: false },
  },
  "csm-plan": {
    sections: [
      "Interface",
      "Activation Boundary",
      "Core Rules",
      "Scale To The Ask",
      "Repository Norms (NORMS.md)",
      "Planning State Machine",
      "Required Plan Document",
    ],
    tmux: true,
    norms: true,
    machine: { section: "Planning State Machine", entryExit: false },
  },
  "csm-bdd-tdd": {
    sections: [
      "Interface",
      "Activation Boundary",
      "Non-Negotiable Rules",
      "Pipeline",
      "Anti-Patterns",
      "Done Criteria",
      "Repository Norms",
    ],
    tmux: true,
    norms: true,
    machine: { section: "Pipeline", entryExit: false },
  },
  "csm-make-tests": {
    sections: [
      "Interface",
      "Tmux Session Bootstrap",
      "Activation Boundary",
      "Core Rules",
      "Write Discipline And File Allowlist",
      "Repository Norms (NORMS.md)",
      "Test Generation State Machine",
      "Required Test Package",
      "Anti-Patterns",
      "Done Criteria",
    ],
    tmux: true,
    norms: true,
    machine: { section: "Test Generation State Machine", entryExit: false },
  },
  "csm-review-python": {
    sections: [
      "Interface",
      "Tmux Session Bootstrap",
      "Activation Boundary",
      "Core Rules",
      "Write Discipline And File Allowlist",
      "Repository Norms (NORMS.md)",
      "Analysis State Machine",
      "Required Report Package",
      "Anti-Patterns",
      "Done Criteria",
    ],
    tmux: true,
    norms: true,
    machine: { section: "Analysis State Machine", entryExit: true },
  },

  "csm-build": {
    sections: [
      "Interface",
      "Activation Boundary",
      "Core Rules",
      "Repository Norms (NORMS.md)",
      "Execution State Machine",
      "Completion Gate",
    ],
    tmux: true,
    norms: true,
    machine: { section: "Execution State Machine", entryExit: false },
  },
  "csm-review": {
    sections: [
      "Interface",
      "Activation Boundary",
      "Core Rules",
      "Write Discipline And File Allowlist",
      "Review State Machine",
      "Review Dimensions",
      "Finding Record",
      "Report Format",
      "Anti-Patterns",
      "Done Criteria",
      "NORMS.md",
      "Tmux Session Bootstrap",
    ],
    tmux: true,
    norms: true,
    machine: { section: "Review State Machine", entryExit: true },
  },
  "csm-scan": {
    sections: [
      "Interface",
      "Tmux Session Bootstrap",
      "When to use",
      "Dimensions",
      "Constraints (non-negotiable)",
      "Testing",
    ],
    tmux: true,
    norms: false,
    machine: null,
  },
  "csm-browse": {
    sections: ["Interface", "When to use this skill", "Verb reference", "Isolation note"],
    tmux: false,
    norms: false,
    machine: null,
  },
  "csm-upload": {
    sections: ["Interface", "Requirements", "Usage"],
    tmux: false,
    norms: false,
    machine: null,
  },
  "csm-deep-research": {
    sections: [
      "Interface",
      "Tmux Session Bootstrap",
      "Activation Boundary",
      "Core Rules",
      "Write Discipline And File Allowlist",
      "Triage",
      "Research State Machine",
      "Required Research Document",
      "Anti-Patterns",
      "Done Criteria",
      "Subagent Resilience",
    ],
    tmux: true,
    norms: false,
    machine: { section: "Research State Machine", entryExit: false },
  },
  "csm-ddd": {
    sections: [
      "Interface",
      "Activation Boundary",
      "Core Rules",
      "Write Discipline And File Allowlist",
      "Repository Norms (NORMS.md)",
      "Analysis State Machine",
      "Required Report And Graph",
      "Testing",
      "Anti-Patterns",
      "Done Criteria",
    ],
    tmux: false,
    norms: true,
    machine: { section: "Analysis State Machine", entryExit: false },
  },
  "csm-autoresearch": {
    sections: [
      "Interface",
      "Activation Boundary",
      "Core Rules",
      "Autoresearch State Machine",
      "Artifact Contracts",
      "Never-Invoke Boundary",
      "Done Criteria",
    ],
    tmux: false,
    norms: false,
    machine: { section: "Autoresearch State Machine", entryExit: false },
  },
};

const CONTRACTS = [
  {
    id: "plan-save-path",
    source: { skill: "csm-plan", needle: ".agents/plans/<date>-<goal-slug>-csm.json" },
    consumers: [{ skill: "csm-build", needle: ".agents/plans/" }],
    rule: "prefix",
  },
  {
    id: "bdd-plan-suffix",
    source: { skill: "csm-bdd-tdd", needle: "-bdd-csm.json" },
    consumers: [{ skill: "csm-build", needle: "-bdd-csm.json" }],
    rule: "exact",
  },
  {
    id: "bdd-json-supersession",
    source: { skill: "csm-bdd-tdd", needle: "typed supersession pointer" },
    consumers: [{ skill: "csm-build", needle: "typed supersession pointer" }],
    rule: "exact",
  },
  {
    id: "ddd-analysis-to-planners",
    source: { skill: "csm-ddd", needle: ".agents/ddd/<yyyy-mm-dd>-<repo-slug>-ddd-report.md" },
    consumers: [
      { skill: "csm-plan", needle: ".agents/ddd/" },
      { skill: "csm-build", needle: ".agents/ddd/" },
    ],
    rule: "prefix",
  },
];

const UPLOAD_SCRIPT_REF = {
  skill: "csm-upload",
  pattern: /csm-[a-z-]+\/scripts\/[A-Za-z0-9._-]+\.mjs/g,
};

const INTERFACES = {
  "csm-grill": {
    entryConditions: [
      "idea shared",
      "explicit request to be grilled, interviewed, or stress-tested",
    ],
    consumes: [
      "rough idea",
      "repository and research evidence",
      "optional csm-deep-research findings when dispatched",
    ],
    produces: ["agreed phased approach document"],
    handoff: ["phase briefs to a separately invoked csm-plan"],
    midPipeline: ["user decisions", "research findings", "explicit agreement"],
  },
  "csm-plan": {
    entryConditions: ["brief or phase brief", "explicit planning request"],
    consumes: [
      "idea or phase brief",
      "repository conventions",
      "review findings",
      "optional csm-deep-research findings when dispatched",
      "optional csm-ddd analysis artifacts when explicitly referenced",
    ],
    produces: ["saved, verified CSM plan"],
    handoff: ["saved plan to csm-bdd-tdd or csm-build"],
    midPipeline: ["research evidence", "critique findings", "verified plan state"],
  },
  "csm-bdd-tdd": {
    entryConditions: ["saved CSM plan", "explicit BDD/TDD mutation request"],
    consumes: ["saved plan", "repository conventions"],
    produces: ["formal spec", "Gherkin scenarios", "unit test designs", "mutated CSM plan"],
    handoff: ["mutated plan to csm-build"],
    midPipeline: ["spec", "approved scenarios", "validation report", "test designs"],
  },
  "csm-build": {
    entryConditions: ["saved CSM plan", "explicit implementation request"],
    consumes: [
      "saved plan",
      "optional NORMS.md",
      "BDD/TDD package when present",
      "optional csm-ddd analysis artifacts when the plan cites them",
    ],
    produces: [
      "verified implementation",
      "delivery evidence; commit only with explicit authorization",
    ],
    handoff: ["delivery evidence to a separately invoked csm-browse"],
    midPipeline: ["task dependencies", "checkpoints", "review findings", "repair evidence"],
  },
  "csm-review": {
    entryConditions: ["repository target", "explicit review, audit, or assessment request"],
    consumes: ["repository at a pinned commit", "optional NORMS.md"],
    produces: ["dated findings report"],
    handoff: [
      "review findings to a subsequent csm-plan run",
      "separate human-mediated dispatch to csm-review-python",
    ],
    midPipeline: ["evidence pack", "finder ledger", "challenge verdicts", "adjudicated findings"],
  },
  "csm-scan": {
    entryConditions: ["repository target", "scan or conventions-analysis request"],
    consumes: ["committed repository declarations"],
    produces: ["NORMS.md"],
    handoff: ["optional conventions input to csm-plan, csm-bdd-tdd, csm-build, or csm-review"],
    midPipeline: ["survey", "deep dimension scans", "enrichment", "deterministic render"],
  },
  "csm-browse": {
    entryConditions: ["need to drive a headful Chromium browser"],
    consumes: ["browser session", "CDP verbs", "delivery target"],
    produces: ["screenshots", "videos", "DOM, console, network, or performance evidence"],
    handoff: ["evidence files to a separately invoked csm-upload"],
    midPipeline: ["isolated Chromium session", "session verbs", "session cleanup"],
  },
  "csm-upload": {
    entryConditions: ["evidence files ready", "configured GitHub Pages destination"],
    consumes: ["screenshots, videos, or evidence files", "GitHub configuration"],
    produces: ["dated GitHub Pages demo page"],
    handoff: ["expected evidence URL to the user; verify Pages deployment separately"],
    midPipeline: ["clone or pull", "copy files", "generate index", "commit and push"],
  },
  "csm-deep-research": {
    entryConditions: [
      "research question or topic",
      "explicit deep-research request",
      "dispatch from csm-grill or csm-plan",
    ],
    consumes: [
      "research question",
      "retrievable sources (web, docs, repositories)",
      "browser-rendered retrieval via csm-browse fallback (JS-only pages)",
    ],
    produces: [
      "run-ID-suffixed research document at .agents/research/<date>-<slug>-<run-id>-research.md",
      "optional declared run artifacts under .agents/research/artifacts/",
    ],
    handoff: [
      "research document and any declared run artifacts to the user or a dispatching csm-grill or csm-plan; parent records and verifies the handoff without writing artifacts",
    ],
    midPipeline: ["subagent dispatches", "findings ledger", "synthesis"],
  },
  "csm-make-tests": {
    entryConditions: ["repository checkout at a pinned commit", "optional change-surface scope"],
    consumes: [
      "repository working tree",
      "optional NORMS.md conventions",
      "cited research findings under .agents/research/",
    ],
    produces: [
      "executable test files and goldens in the target repository",
      ".agents/tests/<yyyy-mm-dd>-<repo-slug>-tests-ledger.md",
      ".agents/tests/<yyyy-mm-dd>-<repo-slug>-verification.md",
    ],
    handoff: [
      "verified suite, ledger, and verification report to the user or a later explicit csm-build run",
    ],
    midPipeline: [
      "run project test commands",
      "write generated tests and goldens",
      "record approvals",
      "run mutation and performance gates",
    ],
  },
  "csm-review-python": {
    entryConditions: [
      "target python repository checkout at a pinned commit",
      "optional change-surface scope",
      "explicit user consent for any tool installation",
    ],
    consumes: [
      "repository working tree (read-only)",
      "optional NORMS.md conventions",
      "bundled artifacts artifact/python-idiomatic-reviewer-rules.json and artifact/pep20-idiomatic-python-consolidated-research.md",
    ],
    produces: [".agents/doctrine/<yyyy-mm-dd>-<repo-slug>-python-doctrine-review.md"],
    handoff: [
      "single doctrine report (findings + fix guide) to the user or a dispatching csm-review; terminal otherwise",
    ],
    midPipeline: [
      "consent-gated isolated tool runs",
      "severity-mapped findings",
      "single-file report emit",
    ],
  },
  "csm-ddd": {
    entryConditions: [
      "repository at a pinned commit",
      "explicit DDD analysis request",
      "CLI run of the bundled pipeline",
    ],
    consumes: [
      "repository at a pinned commit",
      "optional visible NORMS.md",
      "optional approved question file",
    ],
    produces: [
      ".agents/ddd/<yyyy-mm-dd>-<repo-slug>-ddd-report.md",
      ".agents/ddd/<yyyy-mm-dd>-<repo-slug>-ddd-graph.json",
    ],
    handoff: [
      "report and graph to the user; downstream csm-grill or csm-plan use stays human-mediated",
    ],
    midPipeline: [
      "evidence records",
      "context hypotheses",
      "seam inventory",
      "question/answer nodes",
    ],
  },
  "csm-autoresearch": {
    entryConditions: [
      "explicit autoresearch or evaluator-optimization request",
      "declared target and metric",
    ],
    consumes: [
      "versioned run contract",
      "declared mutation boundary",
      "immutable evaluator policy",
      "bounded datasets",
    ],
    produces: [
      "bounded JSONL evaluator exchanges",
      "append-only trial ledger",
      "atomic report artifact",
    ],
    handoff: ["artifact set to the user for separate approval or later explicit skill invocation"],
    midPipeline: [
      "baseline",
      "proposal screening",
      "hard-gate evaluation",
      "target or hill-climb decision",
      "quarantine and rollback",
    ],
  },
};

// NORMS.md authenticity uses one shared any-of rule across the suite: a
// candidate must contain either marker before it is treated as csm-scan output.
const NORMS_PHRASES = ["Generated by csm-scan", "## Repository Overview"];

// Known artifact format versions (kind -> latest known major). Corpus checks
// fail on markers with an unknown kind or a version newer than recorded here.
const FORMAT_VERSIONS = {
  "csm-plan": 1,
  "csm-review": 1,
  "csm-grill": 1,
  "csm-norms": 1,
  "csm-deep-research": 1,
  "csm-make-tests": 1,
  "csm-review-python": 1,
  "csm-ddd-report": 1,
  "csm-ddd-graph": 1,
  "csm-autoresearch-contract": 1,
  "csm-autoresearch-policy": 1,
  "csm-autoresearch-evaluator-request": 1,
  "csm-autoresearch-evaluator-response": 1,
  "csm-autoresearch-ledger": 1,
  "csm-autoresearch-report": 1,
  "csm-autoresearch-manifest": 1,
  "csm-autoresearch-llm-adapter": 1,
};

// Universal never-invoke matrix (explicit literal, not a shorthand): every
// skill is terminal at its final state; handoff happens only via artifacts
// plus an explicit user invocation. Off-diagonal cells are true; diagonal false.
// Asymmetric by design (D22): the non-dispatch rows carry 9 columns; dispatch rows carry the deep-research column too; the
// csm-grill and csm-plan rows add the csm-deep-research column as false —
// they may dispatch csm-deep-research runs for cited external findings —
// and only the csm-deep-research row adds the self column (expected sets
// derive from filtered row keys, so sibling bullets stay 7- or 8-name).
// Second asymmetry: the csm-deep-research row carries csm-browse as false
// because deep-research may invoke csm-browse solely for browser-rendered
// retrieval of JS-only pages.
// Third asymmetry: the review->analyzer false cell is present because csm-review
// may hand off a separate, human-mediated csm-review-python dispatch.
const NEVER_INVOKE = {
  "csm-bdd-tdd": {
    "csm-bdd-tdd": false,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-browse": {
    "csm-bdd-tdd": true,
    "csm-browse": false,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-build": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": false,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-grill": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": false,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-deep-research": false,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-plan": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": false,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-deep-research": false,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-review": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": false,
    "csm-scan": true,
    "csm-upload": true,
    "csm-make-tests": true,
    "csm-review-python": false,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-scan": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": false,
    "csm-upload": true,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-upload": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": false,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-deep-research": {
    "csm-bdd-tdd": true,
    "csm-browse": false,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-deep-research": false,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-make-tests": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-deep-research": true,
    "csm-make-tests": false,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-review-python": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-deep-research": true,
    "csm-make-tests": true,
    "csm-review-python": false,
    "csm-ddd": true,
    "csm-autoresearch": true,
  },
  "csm-ddd": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-deep-research": true,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": false,
    "csm-autoresearch": true,
  },
  "csm-autoresearch": {
    "csm-bdd-tdd": true,
    "csm-browse": true,
    "csm-build": true,
    "csm-grill": true,
    "csm-plan": true,
    "csm-review": true,
    "csm-scan": true,
    "csm-upload": true,
    "csm-deep-research": true,
    "csm-make-tests": true,
    "csm-review-python": true,
    "csm-ddd": true,
    "csm-autoresearch": false,
  },
};

export {
  MANIFEST,
  CONTRACTS,
  UPLOAD_SCRIPT_REF,
  INTERFACES,
  NEVER_INVOKE,
  FORMAT_VERSIONS,
  NORMS_PHRASES,
};
