#!/usr/bin/env node
"use strict";

// Installs the repo's git hooks via lefthook under core.hooksPath (single
// tracked copy; no per-clone duplication). The committed lefthook shim at
// scripts/hooks/pre-commit is generated by `lefthook install --force`; all
// gate logic lives in .lefthook.yml. Uninstall: node scripts/install-hooks.mjs --uninstall.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const root = execFileSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8" }).trim();
const hooksDir = path.join(root, "scripts", "hooks");

function run(cmd, args, opts = {}) {
  return execFileSync(cmd, args, { cwd: root, stdio: "inherit", ...opts });
}

function uninstall() {
  run("pnpm", ["exec", "lefthook", "uninstall"], { stdio: "inherit" });
  try {
    execFileSync("git", ["config", "--unset", "core.hooksPath"], { cwd: root });
  } catch {
    // core.hooksPath already absent — nothing to unset
  }
  execFileSync("git", ["checkout", "--", "scripts/hooks/pre-commit"], { cwd: root });
  console.log("install-hooks: core.hooksPath unset; lefthook hooks removed; tracked shim restored");
}

if (process.argv.includes("--uninstall")) {
  uninstall();
  process.exit(0);
}

run("pnpm", ["install", "--frozen-lockfile", "--ignore-scripts"]);

execFileSync("git", ["config", "core.hooksPath", "scripts/hooks"], { cwd: root });

run("pnpm", ["exec", "lefthook", "install", "--force"]);

// L14: lefthook's generated shim embeds the local pnpm-store absolute path
// (user home + version-pinned layout). Normalize the committed copy to the
// portable branches only — the generic fallbacks resolve correctly on every
// machine, so the machine-specific lines add churn and leak usernames.
const shimPath = path.join(hooksDir, "pre-commit");
if (fs.existsSync(shimPath)) {
  const original = fs.readFileSync(shimPath, "utf8");
  // Drop the machine-specific elif arm structurally (condition line + its
  // `then` + the exec body line) so the generated shell stays valid.
  const lines = original.split("\n");
  const kept = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (lines[i].includes("/.pnpm/lefthook-")) {
      let removed = 1;
      i += 1;
      while (i < lines.length && removed < 3) {
        const t = lines[i].trim();
        if (t === "then" || t.endsWith('lefthook "$@"')) {
          removed += 1;
          i += 1;
        } else break;
      }
      i -= 1;
      continue;
    }
    kept.push(lines[i]);
  }
  const normalized = kept.join("\n");
  if (normalized !== original) {
    fs.writeFileSync(shimPath, normalized);
    console.log("install-hooks: normalized pre-commit shim (removed machine-specific paths)");
  }
}

const oldHook = path.join(hooksDir, "pre-commit.old");
if (fs.existsSync(oldHook)) {
  fs.rmSync(oldHook);
  console.log("install-hooks: removed one-time legacy pre-commit.old");
}

const active = execFileSync("git", ["config", "core.hooksPath"], {
  encoding: "utf8",
  cwd: root,
}).trim();
console.log(`install-hooks: core.hooksPath = ${active}`);
run("pnpm", ["exec", "lefthook", "validate"]);
console.log(
  "install-hooks: lefthook pre-commit gate active (bypass: git commit --no-verify; uninstall: node scripts/install-hooks.mjs --uninstall)",
);
