#!/usr/bin/env node
'use strict';

// Installs the repo's git hooks via lefthook under core.hooksPath (single
// tracked copy; no per-clone duplication). The committed lefthook shim at
// scripts/hooks/pre-commit is generated by `lefthook install --force`; all
// gate logic lives in .lefthook.yml. Uninstall: node scripts/install-hooks.mjs --uninstall.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const root = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
const hooksDir = path.join(root, 'scripts', 'hooks');

function run(cmd, args, opts = {}) {
  return execFileSync(cmd, args, { cwd: root, stdio: 'inherit', ...opts });
}

function uninstall() {
  run('pnpm', ['exec', 'lefthook', 'uninstall'], { stdio: 'inherit' });
  execFileSync('git', ['config', '--unset', 'core.hooksPath'], { cwd: root });
  console.log('install-hooks: core.hooksPath unset; lefthook hooks removed');
}

if (process.argv.includes('--uninstall')) {
  uninstall();
  process.exit(0);
}

run('pnpm', ['install', '--frozen-lockfile', '--ignore-scripts']);

execFileSync('git', ['config', 'core.hooksPath', 'scripts/hooks'], { cwd: root });

run('pnpm', ['exec', 'lefthook', 'install', '--force']);

const oldHook = path.join(hooksDir, 'pre-commit.old');
if (fs.existsSync(oldHook)) {
  fs.rmSync(oldHook);
  console.log('install-hooks: removed one-time legacy pre-commit.old');
}

const active = execFileSync('git', ['config', 'core.hooksPath'], { encoding: 'utf8', cwd: root }).trim();
console.log(`install-hooks: core.hooksPath = ${active}`);
run('pnpm', ['exec', 'lefthook', 'validate']);
console.log('install-hooks: lefthook pre-commit gate active (bypass: git commit --no-verify; uninstall: node scripts/install-hooks.mjs --uninstall)');
